# Production mode toggle
production: true
http:
  # HTTP server listen port
  listen: ':80'

redis:
  # Redis connection URL
  url: 'redis://user:password@localhost:6789/3?dial_timeout=3&db=1&read_timeout=6s&max_retries=2'

log:
  # Log level
  level: debug

search:
  # Ignore of common verbs and articles in English language for search.
  ignore_common_words: true

storage:
  # Files upload directory
  uploads_dir: path/to/uploads
